# Generated by Django 6.0.6 on 2026-07-08 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('origin_location', models.CharField(blank=True, max_length=180)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('family_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_branches', to='lineage.clan')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_branches', to='communities.community')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LineageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('record_type', models.CharField(choices=[('family_tree', 'Family tree'), ('oral_history', 'Oral history'), ('migration', 'Migration'), ('biography', 'Biography'), ('archive', 'Archive')], default='family_tree', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=220)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('community', 'Community'), ('private', 'Private')], default='public', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='viewable_lineage_records', to=settings.AUTH_USER_MODEL)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_records', to='lineage.clan')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_records', to='communities.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lineage_records', to=settings.AUTH_USER_MODEL)),
                ('editor_users', models.ManyToManyField(blank=True, related_name='editable_lineage_records', to=settings.AUTH_USER_MODEL)),
                ('family_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_records', to='lineage.familybranch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=220)),
                ('file_url', models.URLField(blank=True)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lineage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_records', to='lineage.lineagerecord')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Ancestor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('gender', models.CharField(choices=[('unknown', 'Unknown'), ('female', 'Female'), ('male', 'Male')], default='unknown', max_length=32)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lineage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='lineage.lineagerecord')),
            ],
            options={
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='lineage.clan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_villages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lineagerecord',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_records', to='lineage.village'),
        ),
        migrations.AddField(
            model_name='familybranch',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_branches', to='lineage.village'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['name'], name='lineage_vil_name_cbcc60_idx'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(fields=('name', 'clan'), name='unique_village_name_per_clan'),
        ),
        migrations.AddIndex(
            model_name='lineagerecord',
            index=models.Index(fields=['record_type'], name='lineage_lin_record__0cb75b_idx'),
        ),
        migrations.AddIndex(
            model_name='lineagerecord',
            index=models.Index(fields=['visibility'], name='lineage_lin_visibil_a0f687_idx'),
        ),
        migrations.AddIndex(
            model_name='lineagerecord',
            index=models.Index(fields=['status'], name='lineage_lin_status_e7d2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='lineagerecord',
            index=models.Index(fields=['created_at'], name='lineage_lin_created_132b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='familybranch',
            index=models.Index(fields=['family_name'], name='lineage_fam_family__235428_idx'),
        ),
    ]
