# Generated by Django 6.0.6 on 2026-07-06 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['user_a', 'connected_at'], name='connections_user_a__eb631b_idx'), models.Index(fields=['user_b', 'connected_at'], name='connections_user_b__ce1e81_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user_a', models.F('user_b')), _negated=True), name='connection_users_different'), models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_connection_pair')],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connection_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='connections_sender__187b65_idx'), models.Index(fields=['receiver', 'status'], name='connections_receive_bd5aa9_idx'), models.Index(fields=['status', 'created_at'], name='connections_status_e54e3a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='connection_request_sender_receiver_different'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver'), name='unique_pending_directed_connection_request')],
            },
        ),
        migrations.CreateModel(
            name='PersonRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('recommended_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'recommended_user__full_name'],
                'indexes': [models.Index(fields=['user', 'score'], name='connections_user_id_adb048_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('recommended_user')), _negated=True), name='person_recommendation_users_different'), models.UniqueConstraint(fields=('user', 'recommended_user'), name='unique_person_recommendation')],
            },
        ),
    ]
