# Generated by Django 6.0.6 on 2026-07-08 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('meeting', 'Meeting'), ('celebration', 'Celebration'), ('fundraiser', 'Fundraiser'), ('religious', 'Religious'), ('education', 'Education'), ('sports', 'Sports'), ('other', 'Other')], default='meeting', max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=80)),
                ('location_name', models.CharField(blank=True, max_length=220)),
                ('virtual_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communities.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('interested', 'Interested'), ('declined', 'Declined')], default='attending', max_length=32)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['community', 'status', 'starts_at'], name='events_even_communi_c78444_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='events_even_categor_aca11d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'starts_at'], name='events_even_created_809bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_c5a858_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['user', 'responded_at'], name='events_even_user_id_341a9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_rsvp_per_user'),
        ),
    ]
