# Generated by Django 6.0.6 on 2026-07-02 14:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('community_type', models.CharField(choices=[('church', 'Church'), ('mosque', 'Mosque'), ('neighborhood', 'Neighborhood'), ('school', 'School'), ('family', 'Family'), ('professional', 'Professional'), ('village', 'Village'), ('clan', 'Clan')], default='family', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite only')], default='public', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=32)),
                ('color_key', models.CharField(blank=True, max_length=60)),
                ('banner_key', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('president', 'President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('officer', 'Officer'), ('member', 'Member')], default='member', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('requested', 'Requested'), ('suspended', 'Suspended'), ('left', 'Left')], default='active', max_length=32)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contribution_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['community__name', 'user__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['community_type'], name='communities_communi_37bec0_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['visibility'], name='communities_visibil_935cec_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['status'], name='communities_status_82971c_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['role'], name='communities_role_775669_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['status'], name='communities_status_89dd29_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['joined_at'], name='communities_joined__dc056c_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitymembership',
            constraint=models.UniqueConstraint(fields=('user', 'community'), name='unique_user_community_membership'),
        ),
    ]
