# Generated by Django 6.0.6 on 2026-07-08 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('hidden', 'Hidden')], default='active', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='communities.community')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden')], default='active', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feeds.forumpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=32)),
                ('file_url', models.URLField()),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden')], default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='communities.community')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='published', max_length=32)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='communities.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['community', 'status', 'created_at'], name='feeds_annou_communi_b20ed7_idx'), models.Index(fields=['is_pinned'], name='feeds_annou_is_pinn_e19e7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityBusiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('logo_url', models.URLField(blank=True)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden')], default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='communities.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['community', 'status', 'name'], name='feeds_commu_communi_ed60ab_idx'), models.Index(fields=['category'], name='feeds_commu_categor_2ed4ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['community', 'status', 'created_at'], name='feeds_forum_communi_0e269d_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', 'created_at'], name='feeds_forum_author__123722_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['is_pinned'], name='feeds_forum_is_pinn_23e324_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['post', 'status', 'created_at'], name='feeds_forum_post_id_699b13_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['author', 'created_at'], name='feeds_forum_author__f81df6_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['community', 'status', 'created_at'], name='feeds_galle_communi_ef7c75_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['media_type'], name='feeds_galle_media_t_734206_idx'),
        ),
    ]
